# Generated by Django 2.0.9 on 2018-11-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='points_events',
            field=models.IntegerField(default=2),
        ),
    ]
