# Generated by Django 2.0.9 on 2018-11-30 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_challenge_beat_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='beat_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challenge',
            name='goal',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='challenge',
            name='porcent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challenge',
            name='total_events',
            field=models.IntegerField(default=0),
        ),
    ]
