# Generated by Django 2.0.9 on 2018-11-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_challenge_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
