# Generated by Django 2.0.9 on 2018-11-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0008_challenge_des_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='des_event',
        ),
        migrations.AddField(
            model_name='challenge',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
