# Generated by Django 2.0.9 on 2018-11-30 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0009_auto_20181130_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='image',
        ),
    ]
